"""
Local LLM client service.

This module provides a small abstraction layer to communicate with
a locally running Ollama server.

The rest of the application should use this service instead of calling
Ollama directly. This keeps the LLM integration isolated, easier to test,
and easier to replace later with another local model provider if needed.
"""

import requests

from app.config import OLLAMA_BASE_URL, OLLAMA_MODEL


class LLMClientError(Exception):
    """
    Custom exception for errors related to the local LLM client.

    This exception is raised when the application cannot communicate with
    the local Ollama server or when the server returns an unexpected response.
    """

    pass


def generate_text(prompt: str) -> str:
    """
    Sends a prompt to the configured local LLM and returns the generated text.

    Args:
        prompt: The complete prompt that will be sent to the local model.

    Returns:
        The text generated by the configured local LLM.

    Raises:
        LLMClientError: If the prompt is empty, if Ollama is not reachable,
        or if the response from Ollama is invalid.
    """
    if not prompt or not prompt.strip():
        raise LLMClientError("Prompt cannot be empty.")

    endpoint = f"{OLLAMA_BASE_URL}/api/generate"

    payload = {
        "model": OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False,
    }

    try:
        response = requests.post(endpoint, json=payload, timeout=120)
        response.raise_for_status()
    except requests.exceptions.RequestException as error:
        raise LLMClientError(f"Error communicating with local LLM: {error}") from error

    data = response.json()

    generated_text = data.get("response")

    if generated_text is None:
        raise LLMClientError("Invalid response from local LLM. Missing 'response' field.")

    return generated_text.strip()