"""
Local LLM client service.

This module provides a small abstraction layer to communicate with
a locally running Ollama server.

The rest of the application should use this service instead of calling
Ollama directly. This keeps the LLM integration isolated, easier to test,
and easier to replace later with another local model provider if needed.

Logging strategy:
- Logs local LLM requests and responses using metadata only.
- Logs model name, endpoint, prompt length and response length.
- Does not log full prompts or generated responses to avoid exposing
  private document content.
"""

import logging

import requests

from app.config import OLLAMA_BASE_URL, OLLAMA_MODEL
from app.logging_config import log_llm_interaction
from app.services.ollama_transport import OllamaTransportError, post_json

logger = logging.getLogger(__name__)


class LLMClientError(Exception):
    """
    Custom exception for errors related to the local LLM client.

    This exception is raised when the application cannot communicate with
    the local Ollama server or when the server returns an unexpected response.
    """

    pass


def generate_text(prompt: str) -> str:
    """
    Sends a prompt to the configured local LLM and returns the generated text.

    Args:
        prompt: The complete prompt that will be sent to the local model.

    Returns:
        The text generated by the configured local LLM.

    Raises:
        LLMClientError: If the prompt is empty, if Ollama is not reachable,
        or if the response from Ollama is invalid.
    """
    if not prompt or not prompt.strip():
        logger.warning("Local LLM request skipped because prompt is empty.")
        raise LLMClientError("Prompt cannot be empty.")

    endpoint = f"{OLLAMA_BASE_URL}/api/generate"

    payload = {
        "model": OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False,
        "think": False,
    }

    logger.info(
        "Sending prompt to local LLM. model=%s endpoint=%s prompt_length=%s",
        OLLAMA_MODEL,
        endpoint,
        len(prompt),
    )

    try:
        data = post_json(endpoint, payload, requester=requests.post)
    except OllamaTransportError as error:
        logger.error(
            "Error communicating with local LLM. endpoint=%s model=%s error=%s",
            endpoint,
            OLLAMA_MODEL,
            error,
        )
        raise LLMClientError(f"Error communicating with local LLM: {error}") from error

    logger.info(
        "Local LLM response metadata. model=%s response_length=%s "
        "thinking_length=%s done_reason=%s prompt_eval_count=%s eval_count=%s",
        OLLAMA_MODEL,
        len(data.get("response", "")),
        len(data.get("thinking", "")),
        data.get("done_reason"),
        data.get("prompt_eval_count"),
        data.get("eval_count"),
    )

    generated_text = data.get("response")

    if generated_text is None:
        logger.error(
            "Invalid response from local LLM. Missing response field. model=%s",
            OLLAMA_MODEL,
        )
        raise LLMClientError(
            "Invalid response from local LLM. Missing 'response' field."
        )

    generated_text = generated_text.strip()

    if not generated_text:
        logger.error(
            "Local LLM returned an empty response. model=%s",
            OLLAMA_MODEL,
        )
        raise LLMClientError("The local LLM returned an empty response.")

    logger.info(
        "Local LLM response received. model=%s response_length=%s",
        OLLAMA_MODEL,
        len(generated_text),
    )

    log_llm_interaction(
        prompt=prompt,
        response=generated_text,
        model=OLLAMA_MODEL,
    )

    return generated_text
