"""
Document summarization service.

This module provides the logic required to summarize supported local
documents using the configured local LLM.

It connects three parts of the application:
1. The document loader, which reads local .txt and .md files.
2. The prompt template, which defines how the model should summarize.
3. The local LLM client, which sends the prompt to Ollama.
"""

from pathlib import Path

from app.config import BASE_DIR
from app.services.document_loader import read_document
from app.services.llm_client import generate_text


PROMPT_PATH = BASE_DIR / "app" / "prompts" / "summarize_prompt.txt"


class SummarizerError(Exception):
    """
    Custom exception for errors related to document summarization.

    This exception is raised when the prompt template cannot be found,
    when a document cannot be read, or when the local LLM cannot generate
    a valid summary.
    """

    pass


def load_summary_prompt_template() -> str:
    """
    Loads the summary prompt template from the prompts folder.

    Returns:
        The summary prompt template as a string.

    Raises:
        SummarizerError: If the prompt template file does not exist.
    """
    if not PROMPT_PATH.exists():
        raise SummarizerError(f"Summary prompt template not found: {PROMPT_PATH}")

    return PROMPT_PATH.read_text(encoding="utf-8")


def build_summary_prompt(document_content: str) -> str:
    """
    Builds the final prompt used to summarize a document.

    Args:
        document_content: The full content of the document to summarize.

    Returns:
        A complete prompt with the document content injected into the template.

    Raises:
        SummarizerError: If the document content is empty.
    """
    if not document_content or not document_content.strip():
        raise SummarizerError("Document content cannot be empty.")

    template = load_summary_prompt_template()

    return template.replace("{document_content}", document_content)


def summarize_document(filename: str) -> str:
    """
    Summarizes a supported local document using the configured local LLM.

    Args:
        filename: The name of the document located in the data/input folder.

    Returns:
        The summary generated by the local LLM.

    Raises:
        FileNotFoundError: If the requested document does not exist.
        ValueError: If the requested document has an unsupported extension.
        SummarizerError: If the prompt cannot be built or the local LLM fails.
    """
    try:
        document_content = read_document(filename)
        prompt = build_summary_prompt(document_content)
        summary = generate_text(prompt)
    except FileNotFoundError:
        raise
    except ValueError:
        raise
    except Exception as error:
        raise SummarizerError(f"Error summarizing document '{filename}': {error}") from error

    return summary