"""
Document summarization service.

This module provides the logic required to summarize supported local
documents using the configured local LLM.

It connects three parts of the application:
1. The document loader, which reads local .txt and .md files.
2. The prompt template, which defines how the model should summarize.
3. The local LLM client, which sends the prompt to Ollama.

Logging strategy:
- Logs summarization flow using operational metadata.
- Logs filename, document length, prompt length and summary length.
- Does not log full document content, full prompt or generated summary
  to avoid exposing private information.
"""

import logging

from app.config import BASE_DIR
from app.services.document_loader import read_document
from app.services.llm_client import generate_text


logger = logging.getLogger(__name__)


PROMPT_PATH = BASE_DIR / "app" / "prompts" / "summarize_prompt.txt"


class SummarizerError(Exception):
    """
    Custom exception for errors related to document summarization.

    This exception is raised when the prompt template cannot be found,
    when a document cannot be read, or when the local LLM cannot generate
    a valid summary.
    """

    pass


def load_summary_prompt_template() -> str:
    """
    Loads the summary prompt template from the prompts folder.

    Returns:
        The summary prompt template as a string.

    Raises:
        SummarizerError: If the prompt template file does not exist.
    """
    logger.info("Loading summary prompt template. path=%s", PROMPT_PATH)

    if not PROMPT_PATH.exists():
        logger.error("Summary prompt template not found. path=%s", PROMPT_PATH)
        raise SummarizerError(f"Summary prompt template not found: {PROMPT_PATH}")

    template = PROMPT_PATH.read_text(encoding="utf-8")

    logger.info(
        "Summary prompt template loaded successfully. template_length=%s",
        len(template),
    )

    return template


def build_summary_prompt(document_content: str) -> str:
    """
    Builds the final prompt used to summarize a document.

    Args:
        document_content: The full content of the document to summarize.

    Returns:
        A complete prompt with the document content injected into the template.

    Raises:
        SummarizerError: If the document content is empty.
    """
    if not document_content or not document_content.strip():
        logger.warning("Summary prompt build skipped because document content is empty.")
        raise SummarizerError("Document content cannot be empty.")

    logger.info(
        "Building summary prompt. document_length=%s",
        len(document_content),
    )

    template = load_summary_prompt_template()
    prompt = template.replace("{document_content}", document_content)

    logger.info(
        "Summary prompt built successfully. prompt_length=%s",
        len(prompt),
    )

    return prompt


def summarize_document(filename: str) -> str:
    """
    Summarizes a supported local document using the configured local LLM.

    Args:
        filename: The name of the document located in the data/input folder.

    Returns:
        The summary generated by the local LLM.

    Raises:
        FileNotFoundError: If the requested document does not exist.
        ValueError: If the requested document has an unsupported extension.
        SummarizerError: If the prompt cannot be built or the local LLM fails.
    """
    logger.info("Document summarization started. filename=%s", filename)

    try:
        document_content = read_document(filename)

        logger.info(
            "Document loaded for summarization. filename=%s document_length=%s",
            filename,
            len(document_content),
        )

        prompt = build_summary_prompt(document_content)
        summary = generate_text(prompt)

    except FileNotFoundError:
        logger.warning(
            "Document summarization failed because file was not found. filename=%s",
            filename,
        )
        raise

    except ValueError:
        logger.warning(
            "Document summarization failed because file extension is unsupported. filename=%s",
            filename,
        )
        raise

    except Exception as error:
        logger.error(
            "Document summarization failed due to internal error. filename=%s error=%s",
            filename,
            error,
        )
        raise SummarizerError(f"Error summarizing document '{filename}': {error}") from error

    logger.info(
        "Document summarization finished successfully. filename=%s summary_length=%s",
        filename,
        len(summary),
    )

    return summary