"""
Local vector storage service.

This module persists document chunks, embeddings, and source metadata in a
local ChromaDB collection. It also performs similarity searches using query
embeddings generated by the application's embedding service.

The database is stored under ``data/chroma`` and must remain outside Git.
The collection uses cosine distance and receives precomputed embeddings, so
ChromaDB does not call an external embedding provider.

Logging strategy:
- Logs collection operations, record counts, filenames, and result counts.
- Does not log document content or full embedding vectors.
"""

import logging

import chromadb

from app.config import CHROMA_COLLECTION_NAME, CHROMA_DIR


logger = logging.getLogger(__name__)

_client = None


class VectorStoreError(Exception):
    """Raised when local vector storage or retrieval cannot be completed."""

    pass


def get_client():
    """
    Opens or reuses the persistent local ChromaDB client.

    The client is shared so the application does not repeatedly open SQLite
    and vector-index files. Call ``close_vector_store`` during application or
    test shutdown to release those resources explicitly.
    """
    global _client

    if _client is None:
        CHROMA_DIR.mkdir(parents=True, exist_ok=True)
        _client = chromadb.PersistentClient(path=str(CHROMA_DIR))

    return _client


def close_vector_store() -> None:
    """Closes the shared ChromaDB client and releases local file handles."""
    global _client

    if _client is not None:
        _client.close()
        _client = None
        logger.info("Local vector store client closed.")


def get_collection():
    """
    Opens the persistent local ChromaDB collection.

    Returns:
        A collection configured for cosine-distance vector search.

    Raises:
        VectorStoreError: If ChromaDB cannot open or create the collection.
    """
    try:
        return get_client().get_or_create_collection(
            name=CHROMA_COLLECTION_NAME,
            embedding_function=None,
            configuration={"hnsw": {"space": "cosine"}},
        )
    except Exception as error:
        logger.error(
            "Unable to open local vector collection. path=%s collection=%s error=%s",
            CHROMA_DIR,
            CHROMA_COLLECTION_NAME,
            error,
        )
        raise VectorStoreError(f"Unable to open local vector collection: {error}") from error


def _validate_chunks_and_embeddings(
    chunks: list[dict],
    embeddings: list[list[float]],
) -> None:
    """Validates chunk records and their corresponding embeddings."""
    if not chunks:
        raise VectorStoreError("At least one chunk is required.")

    if len(chunks) != len(embeddings):
        raise VectorStoreError("Chunk count does not match embedding count.")

    required_fields = {"chunk_id", "filename", "content", "start_char", "end_char"}

    for chunk in chunks:
        missing_fields = required_fields.difference(chunk)

        if missing_fields:
            missing = ", ".join(sorted(missing_fields))
            raise VectorStoreError(f"Chunk metadata is incomplete. Missing: {missing}")

        if not str(chunk["content"]).strip():
            raise VectorStoreError("Chunk content cannot be empty.")

    if any(not isinstance(vector, list) or not vector for vector in embeddings):
        raise VectorStoreError("Embedding vectors cannot be empty.")

    vector_dimension = len(embeddings[0])

    if any(len(vector) != vector_dimension for vector in embeddings):
        raise VectorStoreError("Embedding vector dimensions must be consistent.")


def _build_record_id(chunk: dict) -> str:
    """Builds a stable ChromaDB record ID from source and chunk metadata."""
    return f"{chunk['filename']}::chunk::{chunk['chunk_id']}"


def upsert_chunks(chunks: list[dict], embeddings: list[list[float]]) -> int:
    """
    Creates or updates chunk records in the local vector collection.

    Args:
        chunks: Chunk dictionaries produced by the document chunker.
        embeddings: One precomputed vector for every chunk.

    Returns:
        Number of chunk records written.

    Raises:
        VectorStoreError: If inputs are invalid or persistence fails.
    """
    _validate_chunks_and_embeddings(chunks, embeddings)

    ids = [_build_record_id(chunk) for chunk in chunks]
    documents = [chunk["content"] for chunk in chunks]
    metadatas = [
        {
            "filename": chunk["filename"],
            "chunk_id": chunk["chunk_id"],
            "start_char": chunk["start_char"],
            "end_char": chunk["end_char"],
        }
        for chunk in chunks
    ]

    try:
        collection = get_collection()
        collection.upsert(
            ids=ids,
            embeddings=embeddings,
            documents=documents,
            metadatas=metadatas,
        )
    except VectorStoreError:
        raise
    except Exception as error:
        logger.error(
            "Unable to persist document chunks. record_count=%s error=%s",
            len(chunks),
            error,
        )
        raise VectorStoreError(f"Unable to persist document chunks: {error}") from error

    logger.info(
        "Document chunks persisted. filename=%s record_count=%s vector_dimension=%s",
        chunks[0]["filename"],
        len(chunks),
        len(embeddings[0]),
    )

    return len(chunks)


def query_chunks(
    query_embedding: list[float],
    top_k: int = 3,
) -> list[dict]:
    """
    Retrieves the document chunks closest to a query embedding.

    Args:
        query_embedding: Numeric vector produced for a user question.
        top_k: Maximum number of closest chunks to return.

    Returns:
        Ranked chunk dictionaries containing content, source metadata, and
        the cosine distance reported by ChromaDB.

    Raises:
        VectorStoreError: If inputs are invalid or retrieval fails.
    """
    if not isinstance(query_embedding, list) or not query_embedding:
        raise VectorStoreError("Query embedding cannot be empty.")

    if top_k <= 0:
        raise VectorStoreError("Result count must be greater than zero.")

    try:
        collection = get_collection()
        stored_count = collection.count()

        if stored_count == 0:
            logger.info("Vector search skipped because the collection is empty.")
            return []

        result = collection.query(
            query_embeddings=[query_embedding],
            n_results=min(top_k, stored_count),
            include=["documents", "metadatas", "distances"],
        )
    except VectorStoreError:
        raise
    except Exception as error:
        logger.error("Unable to query local vector collection. error=%s", error)
        raise VectorStoreError(f"Unable to query local vector collection: {error}") from error

    documents = result.get("documents", [[]])[0]
    metadatas = result.get("metadatas", [[]])[0]
    distances = result.get("distances", [[]])[0]

    matches = []

    for document, metadata, distance in zip(documents, metadatas, distances):
        matches.append(
            {
                "filename": metadata["filename"],
                "chunk_id": metadata["chunk_id"],
                "content": document,
                "start_char": metadata["start_char"],
                "end_char": metadata["end_char"],
                "distance": distance,
            }
        )

    logger.info(
        "Vector search completed. requested_results=%s returned_results=%s",
        top_k,
        len(matches),
    )

    return matches


def delete_document_chunks(filename: str) -> None:
    """Deletes every stored chunk associated with a source document."""
    if not filename or not filename.strip():
        raise VectorStoreError("Filename cannot be empty.")

    try:
        collection = get_collection()
        collection.delete(where={"filename": filename})
    except VectorStoreError:
        raise
    except Exception as error:
        logger.error(
            "Unable to delete document chunks. filename=%s error=%s",
            filename,
            error,
        )
        raise VectorStoreError(f"Unable to delete document chunks: {error}") from error

    logger.info("Stored document chunks deleted. filename=%s", filename)


def count_stored_chunks() -> int:
    """Returns the number of chunk records in the local collection."""
    try:
        return get_collection().count()
    except VectorStoreError:
        raise
    except Exception as error:
        raise VectorStoreError(f"Unable to count stored chunks: {error}") from error
