"""
Application logging configuration module.

This module centralizes the logging configuration for Private Doc Agent.

It configures:
1. General application logs written to console and logs/app.log.
2. A dedicated LLM input/output log written to logs/llm_io.log.

Logging strategy:
- General logs are privacy-aware and should avoid storing document content,
  full prompts or generated responses.
- LLM I/O logs intentionally store the full prompt and full model response
  for local debugging and learning purposes.
- LLM I/O logs may contain private document content and must not be committed
  to GitHub.
"""

import logging
from logging.handlers import RotatingFileHandler
from datetime import datetime

from app.config import BASE_DIR


# Directory where local log files will be stored.
LOG_DIR = BASE_DIR / "logs"

# General application log file.
LOG_FILE = LOG_DIR / "app.log"

# Dedicated log file for prompts sent to the LLM and responses received.
LLM_IO_LOG_FILE = LOG_DIR / "llm_io.log"

# Visual separator used to identify different API executions in the log file.
LOG_SEPARATOR = "-" * 96


def setup_logging() -> None:
    """
    Configures application-wide logging.

    The configuration includes:
    - Console logging for development visibility.
    - Rotating file logging for general application logs.
    - A consistent log format with timestamp, level, logger name and message.

    This function should be called once when the FastAPI application starts.
    """
    LOG_DIR.mkdir(parents=True, exist_ok=True)

    log_format = "%(asctime)s | %(levelname)s | %(name)s | %(message)s"

    root_logger = logging.getLogger()
    root_logger.setLevel(logging.INFO)

    # Avoid adding duplicate handlers when Uvicorn reloads the application.
    if root_logger.handlers:
        return

    console_handler = logging.StreamHandler()
    console_handler.setLevel(logging.INFO)
    console_handler.setFormatter(logging.Formatter(log_format))

    file_handler = RotatingFileHandler(
        LOG_FILE,
        maxBytes=1_000_000,
        backupCount=3,
        encoding="utf-8",
    )
    file_handler.setLevel(logging.INFO)
    file_handler.setFormatter(logging.Formatter(log_format))

    root_logger.addHandler(console_handler)
    root_logger.addHandler(file_handler)


def log_execution_separator(logger_name: str = "app.execution") -> None:
    """
    Writes a visual separator line to the application logs.

    This function is useful to visually separate different API executions
    when reviewing logs during local development or debugging.

    The separator starts with a newline so the visual line appears clearly
    separated from the previous log entry.

    Args:
        logger_name: Name of the logger that will write the separator.
    """
    logger = logging.getLogger(logger_name)
    logger.info("\n%s", LOG_SEPARATOR)


def log_llm_interaction(prompt: str, response: str, model: str) -> None:
    """
    Writes the full prompt sent to the LLM and the full model response
    to a dedicated local log file.

    This log is intended only for local debugging and learning purposes.

    Important:
        This file may contain private document content because the prompt
        can include the document text. The logs directory must be excluded
        from Git using .gitignore.

    Args:
        prompt: Full prompt sent to the local LLM.
        response: Full response generated by the local LLM.
        model: Name of the local model used.
    """
    LOG_DIR.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().isoformat(timespec="seconds")

    log_entry = f"""
{LOG_SEPARATOR}
Timestamp: {timestamp}
Model: {model}
Prompt length: {len(prompt)}
Response length: {len(response)}

PROMPT SENT TO MODEL:
{prompt}

MODEL RESPONSE:
{response}
{LOG_SEPARATOR}

"""

    with LLM_IO_LOG_FILE.open("a", encoding="utf-8") as log_file:
        log_file.write(log_entry)